### ISSUE TITLE
Some problems about the code

### ISSUE THREAD

**Issue by neozhaoliang** [roice3/Honeycombs#2]
Hi Roice: 

I can't visit gmail at my office, so excuse me for putting my questions here. I have a few problems while reading your code:

1. What  do the classes in the directory `Experiments` do? Is there any guide for how to using them? Or can they be removed safely?

2. When running the `.exe` binary with your example `.xml` files, the `UHS` part works fine and it does output the 1200x1200 image, but where is the `.pov` output? I can't find it.

Also, I'm trying to tidy up the code. And if you don't mind, I'll upload the code via pulling requests and you can check if I modified it right. OK?

**Comment by roice3** [comment]
Hi Zhao,

(1) Anything in experiments can be ignored or removed safely.  It is one-off code I've done for special projects that haven't been incorporated into the codebase.  I should move them to a separate repo.

(2) I'm not sure what is happening here.  Do you have two .xml files in the same directory as the .exe?  The POV-Ray sample in the latest release should generate a file called "2-4-3-2-3-3_0001.pov", which can then be used in POV-Ray along with the included "H3_sample.pov" file.

https://github.com/roice3/Honeycombs/releases/tag/v17.2

I just downloaded that again and tested, and it worked for me.   Perhaps I should add these sample settings files to the code repo, since you might not be using the download?

Yes, please feel free to send pull requests, and I'll review them and incorporate improvements.  As you are seeing by bravely digging, it could use a lot of tidying!

Best,
Roice

**Comment by neozhaoliang** [comment]
I think I know why I can't find the .pov file now: I'm using a Linux system and your saving command may not work for linux. So which part of code specify the path?

--------------

I find it, just change `@".\"` to `@"./"` :smile:

**Comment by neozhaoliang** [comment]
May be you should rename `Vector3D`  to `Quaternion` and make it a class? I found the name `Vector3D` a bit misleading since `Vector3D` is a quaternion and you may move the quaternion code in `Mobius.cs` to this class. And I think by making it a class you may use static methods and hence some methods can be simpler.

**Comment by roice3** [comment]
Yes, Vector3D is not the correct name.  I've wanted to rename it Vector4D since I added a w coordinate a long time ago.  Quaternion would be a reasonable name as well.

I don't think it'd be safe to switch from a struct to a class at this point, without breaking a bunch of things, because that would change pass-by-value semantics to pass-by-reference.  It could be better starting over but there would be a huge amount of bug entropy if the change was made now.

**Comment by neozhaoliang** [comment]
I have a few more question here: 

1. In the method [`Isometry`](https://github.com/roice3/Honeycombs/blob/master/code/R3/R3.Core/Math/Mobius.cs#L111) in `mobius.cs`, the mobius transformation in the "spherical" case, do you mean the isometry of the Riemann sphere? Shouldn't it be a matrix in SU(2) like 
         a                        b
-conjugate(b)       conjugate(a)

and |a|^2 + |b|^2 = 1?

In your code I saw it is not the case because `D` is 1. I hope I understood you right ...

2. What's [`DNE` ](https://github.com/roice3/Honeycombs/blob/master/code/R3/R3.Core/Geometry/Vector3D.cs#L249) short for?

3. In the [`GreaterThanOrEqual` ](https://github.com/roice3/Honeycombs/blob/master/code/R3/R3.Core/Math/Utils.cs#L35) function, shouldn't it be `d1 > (d2 - Threshold)` ? 

4. In [this line](https://github.com/roice3/Honeycombs/blob/master/code/R3/R3.Core/Geometry/Vector3D.cs#L137), I guess if some component of this and other are both positive infinite, whereas other components all differ no more than `Tolerance` should be implemented instead.

Sorry for bothering you with so many questions, I tried to ask bunch of them in one time, but I certainly have much more to ask ...

**Comment by roice3** [comment]
It's equivalent.  The reason for the different looking formula is that my code constructs a particular isometry:  a CCW rotation about the origin (defined by a point T on the unit circle), then a translation of the origin to P (which in the spherical case is another rotation).  But it is the above in disguise.

In my formula |T|=1 and defines the separate initial rotation.  Consider not doing that initial rotation of Tz, i.e. set T=1.  Then the matrix is more easily recognizable:  f(z) = (z+P)/(-conj(P)\*z+1).  So you can see this is an SU(2) matrix with a = 1 and b = P.  You can think of the compositions as taking y=Tz and plugging y into the simpler formula.

**Comment by neozhaoliang** [comment]
Another question: in `Vector3D.cs`, which of `x,y,z,w` is the real part? In `Vector3D.cs` it seems that a quaternion is represented as `q = xi + yj + zk + w`, but in the fuction `MulQuat` of `Mobius.cs`, it seems that  `q = x + yi + zj + wk ` is used.

**Comment by roice3** [comment]
Truth is I didn't write the Vector class with Quaternions in mind, but as vectors in R^3, which were later extended to R^4 with the addition of the w component.  So I never thought of the 4 scalars mapped onto quaternions.  The reason for the choice in Mobius.cs is because I was following this paper: http://www.mscand.dk/article/viewFile/12036/10052

**Comment by roice3** [comment]
I somehow missed a few of your earlier questions:

(2) DNE stands for "Does Not Exist".  Maybe calling it NaN would have been better, since it returns true for a vector if any of the components are NaNs.
(3) Yes, thanks for catching that bug.  I'll fix this.
(4) Yes, that could be improved, though I haven't found it an issue in practice.  In fact, there is a fundamental problem with that method because Equals uses it but the implementation doesn't match the GetHashCode function (and can't because I want "soft", tolerance-friendly equality checking).  That breaks the rules of hashes, but again, it has worked very well in practice.  If we make changes here, we should consider performance as well since this method is called so much.

Also, I realized in my earlier answer about the isometries that |a|^2 + |b|^2 != 1.  I'm not sure what is up with this yet, but the method does work (as far as moving the origin to P in spherical geometry).  If you figure out what is going on, please let me know.

**Comment by zemora** [comment]
I don't know if this is a bug:  assume `threshold = 1e-6` as in your code, and `u = (0.99*1e6, 0.99*1e-6, 0.99*1e-6, 0.99*1e-6)`. Clearly `u == Vector3D(0, 0, 0, 0)` since each of its component is less than the threshold

**Comment by neozhaoliang** [comment]
I think it's because a translation in the complex plane does not yield an isometry of the Riemann sphere:

`d(z, w) = (|z-w| ) / (sqrt (1 + |z|**2)  * sqrt(1+|w|**2))` 

Clearly this is not invariant under a translation.

**Comment by neozhaoliang** [comment]
The rotation group of the Riemann sphere is `PSU_2(C)`, which is a subgroup of `PSL_2(C) = all Mobius transformations`. Scaling a Mobius transformation gives the same element in `PSL_2(C)`.

**Comment by roice3** [comment]
ah, ok.  So since it is PSU_2(C) instead of SU(2), there are a number of matrices representing the same rotation, and this must just be another of those.  Normalizing must produce the one with |a|^2+|b|^2=1.  Thank you for the clarification!

**Comment by neozhaoliang** [comment]
the program treated two vectors `u, v` to be equal if they both contain `NaN`. Can the rule  be changed so that if either `u` or `v` contains `NaN` then they are unequal?

**Comment by zemora** [comment]
Hi Roice:  May be here is something that can simplify the code: in `util.cs`, you implemented several `IsInfintie` functions, for example
		public static bool IsInfinite( double input )
		{
			return
				double.IsNaN( input ) ||
				double.IsInfinity( input ) ||
				input >= InfiniteScale;
		}

**Comment by neozhaoliang** [comment]
Hi Roice:  sorry that I commented with another accounted :P

May be here is something that can simplify the code: in `util.cs`, you implemented several `IsInfintie` functions, for example

    public static bool IsInfinite( double input )
        {
            return
                double.IsNaN( input ) ||
                double.IsInfinity( input ) ||
                input >= InfiniteScale;
        }

(emm ... did you forgot `input <= -InfinityScale`?)

I think it's easier to implement a `IsFinite` method instead: 

    public static bool IsFinite( double input)
            {    
                   return 
                        -InfiniteScale < input &&
                         input < InfiniteScale     
            }

This is because C# always returns `false` when comparing `NaN` with other floating numbers, and when the input is `double.PositiveInfinity` it obviously returns `False`, then one can write `IsInfinite = ! IsFinite`.

Another question: when comparing two `Vector3D` instances `u, v`, what if we let `u != v` if both `u` and `v`  contain one or more `NaN`s ? Will the code still run ok?  (In your code if they both contain `NaN` then they are equal)

**Comment by neozhaoliang** [comment]
In [this code](https://github.com/roice3/Honeycombs/blob/master/code/R3/R3.Core/Geometry/Vector3D.cs#L377):

    			this = new Vector3D(
				mRot[0,0] * x + mRot[1,0] * y + mRot[2,0] * z,
				mRot[0,1] * x + mRot[1,1] * y + mRot[2,1] * z,
				mRot[0,2] * x + mRot[1,2] * y + mRot[2,2] * z );

Are you sure you are not using the transposed matrix? (the difference is clockwise or anti-clock-wise rotation, and may be  you used clock-wise  everywhere in your code, I guess.)

and the algorithm you used in [computing the intersection of two points](https://github.com/roice3/Honeycombs/blob/master/code/R3/R3.Core/Geometry/Euclidean2D.cs#L66) may be improved: 
We want to find two real numbers r, s such that

     p1 + r (p2 - p1) = p3 + s(p4 - p3)

 which is the same as

          [ dx1  -dx ][ r ] = [ x-x1 ]
          [ dy1  -dy ][ s ] = [ y-y1 ]
    
 whose can be easily solved.

see [this link](http://geomalgorithms.com/a05-_intersect-1.html) for a discussion.

**Comment by roice3** [comment]
These are all good observations and suggestions.  Perhaps we should start opening issues for them so they can be addressed over time by me, you, or some other developer.  Are the current behaviors blocking your development in any way?

**Comment by neozhaoliang** [comment]
I'm reading your coding, trying to understand the logic and post my questions here to check if I got you right. Currently I haven't got the big picture of the whole project (and I'm still a beginner in C#), so I wont' begin pulling requests until I'm sure how it works.

A confusing thing is about how you deal with `infinity` and `nan`. Some times you check if the result is zero (for example normalizing a vector) but do not check if it is infinity or nan and vice versa.

**Comment by roice3** [comment]
The history of the Infinity/NaN checking relates to MagicTile, and the checking was added based on situations I encountered there, mainly for 2D spherical geometry stereographically projected to the plane.  So for instance, I never ran into an issue with things getting projected to -Infinity, so that check wasn't added.  I also haven't run into the situation of attempting to normalize a vector with infinities in it, and I'm not sure what the behavior should be - for this code, probably an error situation like trying to normalize the zero vector.  With respect to the H^3 honeycombs, infinities don't come into play a great deal (one place I can think of them being relevant is applying Mobius transformations to the UHS boundary images), so if you are trying to get the big picture of things, I wouldn't get too hung up on these details.  Behaviors can be somewhat arbitrary.  For example, I decided to consider vectors with any NaNs completely ill-formed, so I didn't care if one or all of the components were NaN.  They are all just "bad" as far as I was concerned.

Regarding the matrix, if it is a CW rotation instead of CCW I think that should be documented in the method comments.  It is unfortunate consistency-wise if I did it that way.

And the line-line intersection method being done geometrically rather than solving a system of equations was just another choice of mine.  In general, I found it easier to approach things this way because of singularities that can happen when solving the equations.

**Comment by neozhaoliang** [comment]
So if I'm only interested in generating H3 honeycombs, I can ignore vectors with `NaN` and `infinity` components? For example when comparing two vectors or hashing a vector, I need not treat these two cases?

**Comment by neozhaoliang** [comment]
I saw you represented a circle inversion by caching the action of the 3 points on it. Why not simply represent a inversion by a mobius transformation and the conjugation? So an isometry can be represented by a mobius transformation and `conjugate = true or false` instead of by a mobius transformation and a `circle` instance.

**Comment by neozhaoliang** [comment]
I pulled a request with another account (which I didn't notice when I was puling that, but let it be there).

So if I'm only interested in the H3 honeycombs, can I just use `inf` instead of using a self-defined infinite scale `InfiniteScale`? Can the  `NaN` checking be removed from the comparing && hashing of the vectors?

And here is something I could not understand when reading `Isometry.cs`: an isometry is either a Mobius transformation (orientation preserving) or a inversion about a circle (orientation reversing) , and the latter can be represented as the `conjugate()` operation on the complex plane plus a  Mobius transformation. So why not represent an isometry simply using a Mobius transformation `m` and a property like `conjugate = true/false`? Then an isometry `I` is either `I = m` or `I = I * conj`.

It seem that you used the representation  `I=m` or `I = inv * m` where `inv` is the inversion about a circle.

Even with this representation, for applying circle inversions you first transform the circle to the unit circle, apply inversion about the unit circle, and then transform back. Why not directly use the inversion formula 

```
(w - center) * (z - center).conjugate()  = radius**2
```
? Did I got something wrong?

**Comment by roice3** [comment]
Hi Zhao, I emailed you yesterday about some of this, so I'll copy that here in case you didn't see it.

> 
I got a few notifications of questions, but don't see them online so I'll just answer in email here.  Maybe you deleted your questions? 

> 
So if I'm only interested in generating H3 honeycombs, I can ignore vectors with NaN and infinity components? For example when comparing two vectors or hashing a vector, I need not treat these two cases?
> 

If you are working in the Poincare model, this is pretty much true.   If you are seeing vectors with NaN and Infinity components in your debugging, it might represent something that is exercising the code beyond its current capabilities.  If you have a honeycomb with an ideal point at the north pole, it will go to infinity in the UHS model, so some situations might arise where you'd see these.  I'd be interested to know more specifically what your goals are in digging into this code.  That might help us moving forward.

> 
I saw you represented a circle inversion by caching the action of the 3 points on it. Why not simply represent a inversion by a mobius transformation and the conjugation? So an isometry can be represented by a mobius transformation and conjugate = true or false instead of by a mobius transformation and a circle instance.
> 

That is likely a better representation in retrospect.  This history of this is tied up with MagicTile as well, and the fact that I was learning about Mobius transformations and Isometries at the time.  Using a generalized circle does give some flexibility in that you have more options for how to do the inversion.  That was convenient in MagicTile, but it certainly could have been done as you describe.  So when you ask "why?" on things like this, I don't always have the best answer.  I was trying to make things work, and this is the way that it evolved.  With multiple choices, I had to pick one based on my best understanding at the time.
>

Another question based on your new comments...  Why do you want to remove the NaN checking?  It doesn't hurt anything to leave it there.  Similarly for the InfiniteScale checking.

**Comment by roice3** [comment]
Hi Zhao, I emailed you yesterday, and I'll copy here in case you didn't see it:

> I got a few notifications of questions, but don't see them online so I'll just answer in email here.  Maybe you deleted your questions? 
> 

> > So if I'm only interested in generating H3 honeycombs, I can ignore vectors with NaN and infinity components? For example when comparing two vectors or hashing a vector, I need not treat these two cases?

> 
> If you are working in the Poincare model, this is pretty much true.   If you are seeing vectors with NaN and Infinity components in your debugging, it might represent something that is exercising the code beyond its current capabilities.  If you have a honeycomb with an ideal point at the north pole, it will go to infinity in the UHS model, so some situations might arise where you'd see these.  I'd be interested to know more specifically what your goals are in digging into this code.  That might help us moving forward.
> 
> 

> > I saw you represented a circle inversion by caching the action of the 3 points on it. Why not simply represent a inversion by a mobius transformation and the conjugation? So an isometry can be represented by a mobius transformation and conjugate = true or false instead of by a mobius transformation and a circle instance.

> 
> That is likely a better representation in retrospect.  This history of this is tied up with MagicTile as well, and the fact that I was learning about Mobius transformations and Isometries at the time.  Using a generalized circle does give some flexibility in that you have more options for how to do the inversion.  That was convenient in MagicTile, but it certainly could have been done as you describe.  So when you ask "why?" on things like this, I don't always have the best answer.  I was trying to make things work, and this is the way that it evolved.  With multiple choices, I had to pick one based on my best understanding at the time.

**Comment by roice3** [comment]
Another question after your last post:  Why do you want to remove the NaN handling?  It doesn't hurt anything to leave it there.  Similarly for the InfiniteScale checking.  I don't understand your motivation to change it.

**Comment by neozhaoliang** [comment]
Hi Roice: In your google doc you said 

```don’t waste your time digging into some of the other “H3” files in the directory with H3Utils.cs.```

What are the files exactly you used in that directory? I see `H3.cs` is also used but it seems that lots of code in it are obsolete.

[In this function](https://github.com/roice3/Honeycombs/blob/master/code/R3/R3.Core/Math/Mobius.cs#L180) you constructed the Mobius transformation of hyperbolic type that 'dilates' around a fixed point with scaling factor scale. (Did I got you right?) But in the Poincare disk model the two fixed points of a hyperbolic Mobius transformation are both on the boundary, so [your construction here](https://github.com/roice3/Honeycombs/blob/master/code/R3/R3.Core/Math/Mobius.cs#L96) may be invalid since the fixed point is on the boundary? (since an automorphism of the disc requires the modulus of `B` in the matrix is strictly less than 1)

**Comment by roice3** [comment]
Hi Zhao, I'm going to try to reserve some time in the next month to clean up the "H3" files.  This will be better than trying to point out what is still useful or not, since I can't recall and it will take just as much effort to go figure that out and report it.  There is still some "leakage" into files which are mainly unusued, so I need to pull out what code is referenced and remove the rest.

Regarding your second question, yeah, that scaling utility function may not be a valid operation in the H^2 case, but it should often be valid in the H^3 case when considering the plane as the boundary of the UHS model.  One will need to take care to use it in the appropriate circumstances.  I see a usage in Tile.ShrinkTile where I used it and pointed out that it was incorrect to do so but "works reasonable well for small shrink factors".

**Comment by neozhaoliang** [comment]
Hi Roice: 

I found [this function](https://github.com/roice3/Honeycombs/blob/master/code/R3/R3.Core/Math/Isometry.cs#L141) in `Isometry.cs` get called many times in your program, so it ought to be important in the logic. But when I tried to modify it to do nothing:

```csharp
		public Complex Apply( Complex z )
		{   
                        /* commnt out the core part to make this function do nothing
			z = Mobius.Apply( z );
			if( Reflection != null )
				z = ApplyCachedCircleInversion( z );
                       */
			return z;
		}
```

The program still works and it renders the same results. I don't know why...

Also I tried to rewrite the [* operator of two isometries](https://github.com/roice3/Honeycombs/blob/master/code/R3/R3.Core/Math/Isometry.cs#L88), even if my logic is totally absurd (only matches the input/output datatype), the program still successfully renders the same images ... 

For example I tried to make that function simply returns `i1`:

```csharp
public static Isometry operator *( Isometry i1, Isometry i2 )
		{
                     return i1;
                }
```
And it still works ...

Another functions with this behavior found: the function `Hyperbolic` in `Mobius.py`. I tried to modify it to simply return a wrong function:

```csharp
		public void Hyperbolic( Geometry g, Complex fixedPlus, double scale )
		{
			/*
			// To the origin.
			Mobius m1 = new Mobius();
			m1.Isometry( g, 0, fixedPlus * -1 );

			// Scale.
			Mobius m2 = new Mobius();
			m2.A = scale;
			m2.B = m2.C = 0;
			m2.D = 1;

			// Back.
			//Mobius m3 = m1.Inverse();	// Doesn't work well if fixedPlus is on disk boundary.
			Mobius m3 = new Mobius();
			m3.Isometry( g, 0, fixedPlus );

			// Compose them (multiply in reverse order).
			this = m3 * m2 * m1;
			*/
			// return a wrong function here.
                        Mobius m = new Mobius ();
			m.Isometry (g, 0, fixedPlus);
			this = m;
		}
```
I see this function is (indirectly) called by `Main`, but the compiled program still gives the right output.

**Comment by neozhaoliang** [comment]
I forgot to add more explanations to my [previous PR](https://github.com/roice3/Honeycombs/pull/4):

1.  `app.config` is modified by my ide `mono` on Linux, not by myself, you may ignore it.
2. The following line is redundant in the comparison between two vectors:
  ```csharp
        public bool Compare( Vector3D other, double threshold )
 		{
			// NOTE: This is here because when the vector is infinite, it fails the tolerance checks below.
			if( ( X == other.X ) && ( Y == other.Y ) && ( Z == other.Z ) && W == other.W )
                        ...
               }
  ```

I can understand why you say `it fails the tolerance checks below when the vector is infinite`, this is because your comparison `x == y` is implemented by check if  `Abs(x-y) <= tolerance`, and when `x,y` are both infinite, `x-y` is `NaN`, which returns false. This is the problem here:  to avoid `inf - inf` I changed the code in the `Zero` function in `utils.cs` by checking if 
`x-tolerance <= y <= x+tolerance`, this works for both finite and infinite inputs.

As for `NaN` input, the rule is `C# always returns false in logical operators when NaN is involved`, so you do not need worry about that.

**Comment by neozhaoliang** [comment]
I think it's better to represent 2d lines and 2d circles both with 2x2 matrices:

A  circle with center `z` and radius `r` can be represented as 
```
z/r,   (r^2 - |z|^2)/r
1/r,  -Conjugate(z)/r
```

And a line passing through `z` and with direction vector `n` (`|n|=1`) can be represented as
```
n,     p*Conjugate(n) - n*Conjugate(p),
0,     Conjugate(n)
```
The matrices are normalized to have determinant +-1 , this is useful for avoiding floating explosion when several matrices are multiplied.

Then the inversion of a point `w` about a circle/line with matrix `M` is simply  `M * conj(w)`, and compositions of Mobius transformations and inversions can all be done by multiplying matrices. The advantage of this approach is that you do not need to cache points on them or always check if it's a circle of a line: you only need to implement the entrance and exit: the entrance is check it's a line or a circle when constructing the matrix, and the exit is check it's a line or a circle when getting the center, radius from the matrix.  Reflections about other circles/lines, points inversions about this circle/line, transformation under isometries can all be done by multiplying matrices without worrying about whether it's line or not.

**Comment by neozhaoliang** [comment]
I have a question about the parameter of  the dihedrals (like `2-4-3-2-3-3`): what do these 6 integers mean? How did you construct the fundamental volume of the honeycomb from these 6 numbers?  (May be this would take too long way to explain, so could you give some references?)
I think `Simplex.cs` is relevant but I have difficulties understanding that file. By a simplex what do you mean exactly?
